---
abstract: 'Moose role for generating Data::Verifier profiles from Moose objects.'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  Moose: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Role-Data-Verifier
requires:
  Moose: 0
  Moose::Role: 0
  Test::More: 0
resources:
  repository: https://github.com/gphat/moosex-role-data-verifier
version: 0.01
